### ISSUE TITLE
Effect gravity is not correctly displayed in multiplayer.

### ISSUE THREAD

**Issue by Fisch37** [qouteall/GravityChanger#11] opened 2023-08-07 19:46 UTC
### Minecraft version

1.20.1

### Describe the issue

Running this mod on Multiplayer, other players are not rotated in accordance to their effect-induced gravity. This results in players appearing stuck in the floor.

# Steps to reproduce
1. Set up a multiplayer server (this is expected to also occur in LAN worlds, but is untested)
2. Have two players join the server
3. Give Player A a potion effect such as Up Gravity.
4. See from the Player B's perspective that the orientation of Player A has not changed.

**Comment by qouteall** [comment] 2023-08-22 13:01
I cannot reproduce this issue
![2023-08-22_20 57 15](https://github.com/qouteall/GravityChanger/assets/45908579/4212bb86-21aa-4df9-82a8-2f9e69941d03)

It may be a mod compatibility issue? Can you backup the world, remove all other mods and test again?

**Comment by qouteall** [comment] 2023-08-22 13:02
Can you provide some video about the issue?

**Comment by Fisch37** [comment] 2023-08-22 13:32
I'm working on it, but in the meantime: It looks like you're using a Gravity Changer Item. That worked fine in our tests. I'm talking about the potion effects.
I'll post a video, when I have it available

**Comment by qouteall** [comment] 2023-08-22 13:36
I see. I can reproduce now. Video not needed now.

**Comment by Fisch37** [comment] 2023-08-22 13:36
Ah, perfect! Have a great day

**Comment by qouteall** [comment] 2023-08-22 14:33
Fixed in 1.1.1

**Closed as completed by qouteall** 2023-08-22 14:33 UTC
Labels: Fixed in the next version
